### ISSUE TITLE
Is it possible to share the source R code?

### ISSUE THREAD

**Issue by genetic-medicine** [jazoller96/mammalian-methyl-clocks#4]
Dear Joseph,

I would like to use some functionalities but I only know python. So it would be nice if the source code can be shared so that a python code can be replicated. If this is not possible, do you know if there are similar python codes available? 

Thanks!
YH

**Comment by jazoller96** [comment]
Hi YH,

I'm in the processing of publishing this software, and I then plan to submit it to CRAN or a similar repository so it can be easily installed by users.  Unfortunately, I do not plan on publishing the source code until the package has been accepted into a repository, so I apologize that there's no option for using these tools in python.

**Comment by genetic-medicine** [comment]
Thanks for the prompt reply. I surely understand that releasing the code too early may create more problems than it solves. Certainly look forward to having your code in the repository and github.
